language: php

php:
  - 7.0

script:
  - php generator.php

after_success:
  - openssl aes-256-cbc -K $encrypted_baf493f04014_key -iv $encrypted_baf493f04014_iv -in travis_key.enc -out travis_key -d
  - cp travis_key ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git clone git@github.com:holidays-jp/api.git
  - cd api
  - cp -ar ../json/ .
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push origin master

env:
  global:
    - GIT_COMMITTER_NAME=matsuoshi
    - GIT_COMMITTER_EMAIL=matsuoshi@gmail.com
    - GIT_AUTHOR_NAME=matsuoshi
    - GIT_AUTHOR_EMAIL=matsuoshi@gmail.com
    