language: php

php:
  - 7.0

script:
  - php holidaysJP.php
  - phpunit

after_success:
  - openssl aes-256-cbc -K $encrypted_baf493f04014_key -iv $encrypted_baf493f04014_iv -in travis_key.enc -out travis_key -d
  - cp travis_key ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "matsuoshi@gmail.com"
  - git config --global user.name "matsuoshi@Travis CI"
  - git clone git@github.com:holidays-jp/api.git
  - cd api
  - cp -aR ../json/* .
  - git add --all
  - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
  - git push origin master

notifications:
  slack:
    secure: 0qpiWy13dOtskCPdkf6y5uYw+pSU43+5b2GaV85INIZ2I3qFO4g/iMKcpg0Nutw54X0tiQE7sUJpwqX+ibgdr9XZALdHrJ3bnXiqnwpAMiTCcPJ4aw5dX90wFMoSSc/9IX/4EAM7Oj5CLtLxWPkyYGdZT+Mr1pWH6T/ohuIv9N8AtKAQpvCrWHIPOB3rGkSehUdW3hfzd8f2af6yp7Ze20uEZciurys578MtYAcwMzLnH4vI3c6igxUqhqz+bdg8GqfHGoNsD13CLDoQiZJ5mLBPChOvGlaJGYzByE3yIQmmKAQ8I1vc4Tk9sJFe3FwkZfJs+67f40IHz125Ifxdp9zN7HA5mIdyfZsvvduUFZChzKbXsaZecq3d/gAnoP8aYCnsfhZ76g3eiSmMAbqcAVcFFs3qWkiy0i1EsNfR31fGMB5LImT5sdH6Qy1DJwpTnv+qi5nBgEnvSuMeTEPWbjaevO/xYFEI0K4rZ1ltfiKuGeG+tmjO4XkXrQlqRF8GymuKa15d0nXcDBgHSZpoEfgqqi9EOGQju4/BxvxAnBIcjn2vctEbOyZ41wK0apI9bkdxAylrVSrhDbY5WtYJxyAh+jsWksPVByvVZZ9Bz7MV5nbnLktepHiERZE3oNGFteJR4z3MuJwTYqDtoMqiaNx1D53ezZKjRdbj5RFaOWk=
